# Generated by Django 4.1 on 2022-08-16 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='date_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='leave',
            name='date_to',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
