# Generated by Django 4.1 on 2022-08-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmapp', '0002_alter_leave_date_from_alter_leave_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('apply', 'apply'), ('pending', 'pending'), ('approved', 'approved'), ('cancel', 'cancel'), ('reject', 'reject')], default='apply', max_length=20),
        ),
    ]
