# Generated by Django 4.1 on 2022-08-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmapp', '0003_alter_leave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='date_to',
            field=models.DateField(null=True),
        ),
    ]
